from abc import ABC, abstractmethod
from typing import List, Optional, Any
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import BaseMessage


class LLMProvider(ABC):
    @abstractmethod
    def get_chat_model(self, temperature: float = 0.2) -> BaseChatModel:
        """Returns a LangChain compatible chat model instance."""
        pass

    @abstractmethod
    async def generate_response(
        self,
        messages: List[BaseMessage],
        temperature: float = 0.2,
    ) -> str:
        """Generates a text response from the model."""
        pass

    @abstractmethod
    async def generate_stream(
        self,
        messages: List[BaseMessage],
        temperature: float = 0.2,
    ):
        """Yields text chunks progressively as they are generated by the model."""
        pass

